spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
